[package]
name = "Ecample rstored plugin"
version = "0.1.0"
authors = ["Artur Augustyniak <artur@aaugustyniak.pl>"]

[lib]
name = "rustexampleplugin"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.0"